version: "3.8"
services:
  service-questionare:
    build:
      context: ./service-questionare
    volumes:
      - ./service-questionare:/code
    ports:
      - 8000:8000
    depends_on:
      - service-questionare-db

  service-questionare-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    volumes:
      - ./service-questionare-db:/data/db
    ports:
      - 27017:27017 # remove this line on prod

  service-heart-es:
    build:
      context: ./service-heart-es
    volumes:
      - ./service-heart-es:/code
    ports:
      - 8001:8001
